language: csharp
solution: src/Scientist.sln
install:
  - nuget restore src/Scientist.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release src/Scientist.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/Scientist.Tests/bin/Release/Scientist.Tests.dll
